/**  文章目录 */
INSERT INTO article_category(category_id, category_name, create_date, category_delete) VALUES (0, '所有文章', '2017-12-12 18:11:34', 0);
INSERT INTO article_category(category_id, category_name, create_date, category_delete) VALUES (1, '技术分享', '2017-12-12 18:11:34', 0);
INSERT INTO article_category(category_id, category_name, create_date, category_delete) VALUES (2, '项目实战', '2017-12-12 18:11:34', 0);
INSERT INTO article_category(category_id, category_name, create_date, category_delete) VALUES (3, '随笔杂谈', '2017-12-12 18:11:34', 0);

/** 博客文章 */
INSERT INTO blog_details(blog_id, blog_title, blog_author, blog_date, blog_read, blog_summary, blog_html_content, blog_md_content, blog_label, blog_delete, blog_category) VALUES (1, 'Spring Boot 入门指南', 'husen', '2018-02-10 20:22:36', 1280, '从零开始学习 Spring Boot 框架的基础知识，包括自动配置、起步依赖和 Actuator 监控等核心特性。', '<p>Spring Boot 是由 Pivotal 团队提供的全新框架，其设计目的是用来简化新 Spring 应用的初始搭建以及开发过程。</p><p>该框架使用了特定的方式进行配置，从而使开发人员不再需要定义样板化的配置。</p><p>核心特性包括：自动配置、起步依赖、Actuator、命令行界面等。</p>', 'Spring Boot 是由 Pivotal 团队提供的全新框架，其设计目的是用来简化新 Spring 应用的初始搭建以及开发过程。该框架使用了特定的方式进行配置，从而使开发人员不再需要定义样板化的配置。', 'Spring Boot 入门', 0, 1);
INSERT INTO blog_details(blog_id, blog_title, blog_author, blog_date, blog_read, blog_summary, blog_html_content, blog_md_content, blog_label, blog_delete, blog_category) VALUES (2, 'MySQL 索引优化实战', 'husen', '2018-03-15 14:30:00', 960, '深入讲解 MySQL 索引原理及常见优化技巧，通过实际案例分析如何提升查询性能。', '<p>索引是帮助 MySQL 高效获取数据的数据结构。最常见的索引类型是 B+Tree 索引。</p><p>优化要点：</p><ul><li>最左前缀原则</li><li>覆盖索引减少回表</li><li>避免索引失效的常见写法</li><li>合理使用 EXPLAIN 分析执行计划</li></ul>', '索引是帮助 MySQL 高效获取数据的数据结构。优化要点包括最左前缀原则、覆盖索引、避免索引失效等。', 'MySQL 索引 优化', 0, 1);
INSERT INTO blog_details(blog_id, blog_title, blog_author, blog_date, blog_read, blog_summary, blog_html_content, blog_md_content, blog_label, blog_delete, blog_category) VALUES (3, 'Java 多线程编程详解', 'husen', '2018-04-20 09:15:00', 1520, '全面介绍 Java 多线程编程的核心概念，包括线程创建、同步机制、线程池以及常见的并发工具类。', '<p>Java 提供了丰富的多线程支持，从基础的 Thread 类到高级的并发工具类。</p><p>主要内容：</p><ul><li>线程的创建与生命周期</li><li>synchronized 与 Lock 锁机制</li><li>线程池 ThreadPoolExecutor 的使用</li><li>CountDownLatch、CyclicBarrier 等并发工具</li><li>volatile 关键字与内存可见性</li></ul>', 'Java 提供了丰富的多线程支持，本篇全面介绍线程创建、同步机制、线程池以及并发工具类的使用。', 'Java 多线程 并发', 0, 1);
INSERT INTO blog_details(blog_id, blog_title, blog_author, blog_date, blog_read, blog_summary, blog_html_content, blog_md_content, blog_label, blog_delete, blog_category) VALUES (4, '使用 Docker 部署 Java Web 应用', 'husen', '2018-05-10 11:00:00', 830, '手把手教你使用 Docker 容器化部署 Java Web 应用，包括 Dockerfile 编写、镜像构建和容器编排。', '<p>Docker 是一个开源的应用容器引擎，让开发者可以打包他们的应用以及依赖包到一个可移植的容器中。</p><p>步骤：</p><ol><li>编写 Dockerfile</li><li>构建镜像：docker build -t myapp .</li><li>运行容器：docker run -d -p 8080:8080 myapp</li><li>使用 docker-compose 编排多容器应用</li></ol>', 'Docker 让应用部署变得简单高效。本文讲解如何使用 Docker 部署 Java Web 应用的完整流程。', 'Docker 部署 容器', 0, 2);
INSERT INTO blog_details(blog_id, blog_title, blog_author, blog_date, blog_read, blog_summary, blog_html_content, blog_md_content, blog_label, blog_delete, blog_category) VALUES (5, '前后端分离架构设计', 'husen', '2018-06-05 16:45:00', 2100, '探讨前后端分离的架构设计思路，包括 RESTful API 设计规范、JWT 认证方案和跨域问题解决。', '<p>前后端分离已成为现代 Web 开发的主流架构。前端专注 UI 交互，后端专注业务逻辑和数据处理。</p><p>关键技术点：</p><ul><li>RESTful API 设计规范</li><li>JWT Token 认证流程</li><li>CORS 跨域解决方案</li><li>API 版本管理策略</li><li>接口文档自动化（Swagger）</li></ul>', '前后端分离是现代 Web 开发的主流架构。本文探讨 API 设计、JWT 认证和跨域等关键问题的解决方案。', '前后端分离 RESTful API 架构', 0, 2);
INSERT INTO blog_details(blog_id, blog_title, blog_author, blog_date, blog_read, blog_summary, blog_html_content, blog_md_content, blog_label, blog_delete, blog_category) VALUES (6, 'Git 团队协作最佳实践', 'husen', '2018-07-18 10:30:00', 670, '总结团队使用 Git 进行协作开发的最佳实践，包括分支管理策略、代码审查流程和提交规范。', '<p>Git 是当今最流行的分布式版本控制系统，良好的协作规范能大幅提升团队效率。</p><p>推荐实践：</p><ul><li>采用 Git Flow 或 GitHub Flow 分支策略</li><li>提交信息遵循 Conventional Commits 规范</li><li>每个 PR 必须经过 Code Review</li><li>使用 rebase 保持提交历史整洁</li><li>配置 CI/CD 自动化测试与部署</li></ul>', 'Git 团队协作需要规范化的流程。本文分享分支管理、代码审查和提交规范等最佳实践。', 'Git 团队协作 版本控制', 0, 1);
INSERT INTO blog_details(blog_id, blog_title, blog_author, blog_date, blog_read, blog_summary, blog_html_content, blog_md_content, blog_label, blog_delete, blog_category) VALUES (7, 'Redis 缓存实战指南', 'husen', '2018-08-22 13:20:00', 1150, '详细介绍 Redis 在 Java Web 项目中的实际应用场景，包括缓存策略、分布式锁和消息队列。', '<p>Redis 是一个高性能的 key-value 内存数据库，广泛应用于缓存、计数器、分布式锁等场景。</p><p>应用场景：</p><ul><li>热点数据缓存，减轻数据库压力</li><li>使用 Redisson 实现分布式锁</li><li>Session 共享解决集群登录问题</li><li>排行榜、计数器等实时数据统计</li><li>发布订阅模式实现消息队列</li></ul>', 'Redis 是高性能的内存数据库。本文讲解在 Java Web 项目中使用 Redis 实现缓存、分布式锁等方案。', 'Redis 缓存 分布式', 0, 1);

/** 代码库 */
INSERT INTO code_library(code_id, code_title, code_author, code_date, code_read, code_summary, code_html_content, code_md_content, code_label, code_delete, code_category) VALUES (1, 'Java 文件上传工具类', 'husen', '2018-02-10 20:25:38', 520, '一个支持多文件上传、类型校验、大小限制的 Java 文件上传工具类。', '<pre><code>public class FileUploadUtil {\n    public static String upload(MultipartFile file, String savePath) {\n        String fileName = UUID.randomUUID() + getExt(file.getOriginalFilename());\n        File dest = new File(savePath, fileName);\n        file.transferTo(dest);\n        return fileName;\n    }\n}</code></pre>', '一个支持多文件上传、类型校验、大小限制的文件上传工具类。', 'Java 文件上传 工具类', 0, 0);
INSERT INTO code_library(code_id, code_title, code_author, code_date, code_read, code_summary, code_html_content, code_md_content, code_label, code_delete, code_category) VALUES (2, 'MD5 加密工具方法', 'husen', '2018-03-08 09:30:00', 380, 'Java 实现 MD5 加密的工具方法，用于密码存储和校验。', '<pre><code>public static String md5(String input) {\n    MessageDigest md = MessageDigest.getInstance("MD5");\n    byte[] digest = md.digest(input.getBytes("UTF-8"));\n    StringBuilder sb = new StringBuilder();\n    for (byte b : digest) sb.append(String.format("%02x", b));\n    return sb.toString();\n}</code></pre>', 'Java 实现 MD5 加密的工具方法，适用于密码存储场景。', 'MD5 加密 安全', 0, 0);
INSERT INTO code_library(code_id, code_title, code_author, code_date, code_read, code_summary, code_html_content, code_md_content, code_label, code_delete, code_category) VALUES (3, 'JSP 分页标签实现', 'husen', '2018-04-12 15:00:00', 450, '自定义 JSP 分页标签，支持首页、尾页、页码动态生成。', '<pre><code>public class PageTag extends SimpleTagSupport {\n    private int pageNo, pageSize, total;\n    public void doTag() throws JspException, IOException {\n        int totalPages = (total + pageSize - 1) / pageSize;\n        JspWriter out = getJspContext().getOut();\n        for (int i = 1; i <= totalPages; i++) {\n            out.write("<a href=?page=" + i + ">" + i + "</a>");\n        }\n    }\n}</code></pre>', '自定义 JSP 分页标签组件，支持动态页码生成和样式控制。', 'JSP 分页 标签', 0, 0);
INSERT INTO code_library(code_id, code_title, code_author, code_date, code_read, code_summary, code_html_content, code_md_content, code_label, code_delete, code_category) VALUES (4, '数据库连接池配置示例', 'husen', '2018-05-20 11:45:00', 610, '基于 JDBC 的简易数据库连接池实现，支持最大连接数、超时等配置。', '<pre><code>public class SimpleConnectionPool {\n    private List<Connection> pool = new ArrayList<>();\n    private int maxSize = 20;\n    \n    public Connection getConnection() {\n        if (pool.isEmpty()) return createNewConnection();\n        return pool.remove(pool.size() - 1);\n    }\n    \n    public void release(Connection conn) {\n        if (pool.size() < maxSize) pool.add(conn);\n        else conn.close();\n    }\n}</code></pre>', '简易的 JDBC 数据库连接池实现，帮助理解连接池的工作原理。', 'JDBC 连接池 数据库', 0, 0);

/** 版本特性 */
INSERT INTO release_feature(release_id, release_author, release_date, release_number, release_content) VALUES (0, 'admin', '2017-09-30 16:20:29', 'V1.0.3', '<p>1、主页显示版本特性、最近更新及其他栏目导航</p>

<p>2、实现发表博客、查看博客、浏览量统计、选择每页显示的博客数量等</p>

<p>3、实现上传代码至代码库、查看代码组件、浏览量统计、分页显示等</p>

<p>4、实现留言、回复留言、分页浏览功能</p>

<p>5、实现下载、下载统计、联系站长发送邮件等基本功能</p>

<p>6、实现登录注册功能、网站单日访问量与总访问量统计、实现在线人数统计</p>');

/** 用户信息 初始密码均为 123123 */
INSERT INTO user_info(user_id, user_name, user_password, user_email, user_phone, user_age, user_sex, user_address, user_head_url, user_nick_name) VALUES (0, 'husen', 'cf5fe8a4669d7300ddac03170796e012', 'husen@example.com', NULL, NULL, NULL, NULL, NULL, 'husen');
INSERT INTO user_info(user_id, user_name, user_password, user_email, user_phone, user_age, user_sex, user_address, user_head_url, user_nick_name) VALUES (1, 'super_admin', '2f0b3214c90231b9ad9f341bf1df8035', 'super_admin@example.com', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO user_info(user_id, user_name, user_password, user_email, user_phone, user_age, user_sex, user_address, user_head_url, user_nick_name) VALUES (2, 'admin', 'c19380b712c30d00881bc9cfb3c74050', 'admin@example.com', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO user_info(user_id, user_name, user_password, user_email, user_phone, user_age, user_sex, user_address, user_head_url, user_nick_name) VALUES (3, 'zhangsan', 'cf5fe8a4669d7300ddac03170796e012', 'zhangsan@example.com', NULL, NULL, NULL, NULL, NULL, '张三');
INSERT INTO user_info(user_id, user_name, user_password, user_email, user_phone, user_age, user_sex, user_address, user_head_url, user_nick_name) VALUES (4, 'lisi', 'cf5fe8a4669d7300ddac03170796e012', 'lisi@example.com', NULL, NULL, NULL, NULL, NULL, '李四');
INSERT INTO user_info(user_id, user_name, user_password, user_email, user_phone, user_age, user_sex, user_address, user_head_url, user_nick_name) VALUES (5, 'test_user', 'cf5fe8a4669d7300ddac03170796e012', 'test@example.com', NULL, NULL, NULL, NULL, NULL, NULL);

/** 网站访问统计 */
INSERT INTO visit_total(visit_id, visit_date, visit_count) VALUES (0, '2017-09-29', 0);
