/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-05-18 10:18:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zh-CN\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>NovaTech Blog</title>\n");
      out.write("\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("<meta name=\"description\"\n");
      out.write("	content=\"专注于编程、前端、Java、人工智能与开发经验分享的现代技术博客。\">\n");
      out.write("<meta name=\"keywords\"\n");
      out.write("	content=\"Java, SpringBoot, 前端开发, Vue, AI, 编程博客\">\n");
      out.write("<meta name=\"author\" content=\"NovaTech\">\n");
      out.write("\n");
      out.write("<!-- 网站图标 -->\n");
      out.write("<link rel=\"shortcut icon\" href=\"/images/favicon.ico\">\n");
      out.write("\n");
      out.write("<!-- jQuery -->\n");
      out.write("<script src=\"/plugins/jquery/js/jquery-3.2.1.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Bootstrap -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css\">\n");
      out.write("<script\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- 自定义CSS -->\n");
      out.write("<style>\n");
      out.write("* {\n");
      out.write("	margin: 0;\n");
      out.write("	padding: 0;\n");
      out.write("	box-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body {\n");
      out.write("	background: #0f172a;\n");
      out.write("	color: #fff;\n");
      out.write("	font-family: \"PingFang SC\", \"Microsoft YaHei\", sans-serif;\n");
      out.write("	overflow-x: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ===== 顶部 Banner ===== */\n");
      out.write(".hero {\n");
      out.write("	position: relative;\n");
      out.write("	height: 100vh;\n");
      out.write("	background:\n");
      out.write("		linear-gradient(rgba(15, 23, 42, 0.75),\n");
      out.write("		rgba(15, 23, 42, 0.85)),\n");
      out.write("		url('/images/banner/banner-1.jpg') center/cover no-repeat;\n");
      out.write("	display: flex;\n");
      out.write("	align-items: center;\n");
      out.write("	justify-content: center;\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".hero-content h1 {\n");
      out.write("	font-size: 68px;\n");
      out.write("	font-weight: bold;\n");
      out.write("	letter-spacing: 3px;\n");
      out.write("	margin-bottom: 20px;\n");
      out.write("	background: linear-gradient(90deg, #38bdf8, #818cf8);\n");
      out.write("	-webkit-background-clip: text;\n");
      out.write("	-webkit-text-fill-color: transparent;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".hero-content p {\n");
      out.write("	font-size: 22px;\n");
      out.write("	color: #cbd5e1;\n");
      out.write("	margin-bottom: 35px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".hero-btn {\n");
      out.write("	display: inline-block;\n");
      out.write("	padding: 14px 40px;\n");
      out.write("	border-radius: 40px;\n");
      out.write("	background: linear-gradient(90deg, #0ea5e9, #6366f1);\n");
      out.write("	color: white;\n");
      out.write("	font-size: 18px;\n");
      out.write("	text-decoration: none;\n");
      out.write("	transition: 0.3s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".hero-btn:hover {\n");
      out.write("	transform: translateY(-3px);\n");
      out.write("	box-shadow: 0 10px 30px rgba(99, 102, 241, 0.5);\n");
      out.write("	color: white;\n");
      out.write("	text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ===== 内容区域 ===== */\n");
      out.write(".section {\n");
      out.write("	padding: 80px 8%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".section-title {\n");
      out.write("	font-size: 40px;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin-bottom: 50px;\n");
      out.write("	position: relative;\n");
      out.write("	display: inline-block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".section-title:after {\n");
      out.write("	content: \"\";\n");
      out.write("	position: absolute;\n");
      out.write("	left: 0;\n");
      out.write("	bottom: -10px;\n");
      out.write("	width: 70%;\n");
      out.write("	height: 4px;\n");
      out.write("	background: linear-gradient(90deg, #38bdf8, #818cf8);\n");
      out.write("	border-radius: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ===== 卡片 ===== */\n");
      out.write(".blog-card {\n");
      out.write("	background: rgba(255,255,255,0.05);\n");
      out.write("	border-radius: 24px;\n");
      out.write("	overflow: hidden;\n");
      out.write("	backdrop-filter: blur(10px);\n");
      out.write("	transition: 0.35s;\n");
      out.write("	margin-bottom: 30px;\n");
      out.write("	border: 1px solid rgba(255,255,255,0.08);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".blog-card:hover {\n");
      out.write("	transform: translateY(-10px);\n");
      out.write("	box-shadow: 0 15px 40px rgba(0,0,0,0.4);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".blog-card img {\n");
      out.write("	width: 100%;\n");
      out.write("	height: 220px;\n");
      out.write("	object-fit: cover;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".blog-content {\n");
      out.write("	padding: 25px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".blog-content h3 {\n");
      out.write("	font-size: 24px;\n");
      out.write("	margin-bottom: 15px;\n");
      out.write("	font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".blog-content p {\n");
      out.write("	color: #cbd5e1;\n");
      out.write("	line-height: 1.8;\n");
      out.write("	font-size: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".read-btn {\n");
      out.write("	display: inline-block;\n");
      out.write("	margin-top: 20px;\n");
      out.write("	color: #38bdf8;\n");
      out.write("	text-decoration: none;\n");
      out.write("	font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".read-btn:hover {\n");
      out.write("	color: #818cf8;\n");
      out.write("	text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ===== Footer ===== */\n");
      out.write(".footer {\n");
      out.write("	padding: 40px;\n");
      out.write("	text-align: center;\n");
      out.write("	color: #94a3b8;\n");
      out.write("	border-top: 1px solid rgba(255,255,255,0.08);\n");
      out.write("	background: #020617;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ===== 每日一句 ===== */\n");
      out.write(".hitokoto-box {\n");
      out.write("	margin-top: 70px;\n");
      out.write("	padding: 30px;\n");
      out.write("	border-radius: 20px;\n");
      out.write("	background: rgba(255,255,255,0.05);\n");
      out.write("	text-align: center;\n");
      out.write("	font-size: 18px;\n");
      out.write("	color: #e2e8f0;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<!-- Hero Banner -->\n");
      out.write("	<section class=\"hero\">\n");
      out.write("		<div class=\"hero-content\">\n");
      out.write("			<h1>NovaTech Blog</h1>\n");
      out.write("			<p>探索编程 · 人工智能 · 前端开发 · 技术成长</p>\n");
      out.write("			<a href=\"/module/blog.hms\" class=\"hero-btn\">开始阅读</a>\n");
      out.write("		</div>\n");
      out.write("	</section>\n");
      out.write("\n");
      out.write("	<!-- 最新博客 -->\n");
      out.write("	<section class=\"section\">\n");
      out.write("		<h2 class=\"section-title\">最新技术文章</h2>\n");
      out.write("\n");
      out.write("		<div class=\"row\">\n");
      out.write("\n");
      out.write("			<div class=\"col-md-4\">\n");
      out.write("				<div class=\"blog-card\">\n");
      out.write("					<img src=\"/images/blog/blog-1.jpg\">\n");
      out.write("					<div class=\"blog-content\">\n");
      out.write("						<h3>SpringBoot 微服务架构实践</h3>\n");
      out.write("						<p>\n");
      out.write("							从零搭建现代 SpringCloud 微服务体系，包含网关、认证、配置中心与容器部署方案。\n");
      out.write("						</p>\n");
      out.write("						<a href=\"#\" class=\"read-btn\">阅读全文 →</a>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"col-md-4\">\n");
      out.write("				<div class=\"blog-card\">\n");
      out.write("					<img src=\"/images/blog/blog-2.jpg\">\n");
      out.write("					<div class=\"blog-content\">\n");
      out.write("						<h3>Vue3 + Vite 高性能前端</h3>\n");
      out.write("						<p>\n");
      out.write("							深入理解 Vue3 Composition API，并结合 Vite 构建企业级现代化前端项目。\n");
      out.write("						</p>\n");
      out.write("						<a href=\"#\" class=\"read-btn\">阅读全文 →</a>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"col-md-4\">\n");
      out.write("				<div class=\"blog-card\">\n");
      out.write("					<img src=\"/images/blog/blog-3.jpg\">\n");
      out.write("					<div class=\"blog-content\">\n");
      out.write("						<h3>AI 开发工具全面解析</h3>\n");
      out.write("						<p>\n");
      out.write("							介绍 Cursor、Copilot、ChatGPT 等 AI 工具如何提升开发效率与代码质量。\n");
      out.write("						</p>\n");
      out.write("						<a href=\"#\" class=\"read-btn\">阅读全文 →</a>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<!-- 每日一句 -->\n");
      out.write("		<div class=\"hitokoto-box\">\n");
      out.write("			<script\n");
      out.write("				src=\"https://api.lwl12.com/hitokoto/main/get?encode=js&charset=utf-8\"></script>\n");
      out.write("			<div id=\"lwlhitokoto\">\n");
      out.write("				<script>\n");
      out.write("					lwlhitokoto();\n");
      out.write("				</script>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("	</section>\n");
      out.write("\n");
      out.write("	<!-- 最新代码 -->\n");
      out.write("	<section class=\"section\">\n");
      out.write("		<h2 class=\"section-title\">热门开源代码</h2>\n");
      out.write("\n");
      out.write("		<div class=\"row\">\n");
      out.write("\n");
      out.write("			<div class=\"col-md-4\">\n");
      out.write("				<div class=\"blog-card\">\n");
      out.write("					<img src=\"/images/code/code-1.jpg\">\n");
      out.write("					<div class=\"blog-content\">\n");
      out.write("						<h3>Java 权限管理系统</h3>\n");
      out.write("						<p>\n");
      out.write("							基于 SpringBoot + JWT + MySQL 构建的完整后台权限管理项目。\n");
      out.write("						</p>\n");
      out.write("						<a href=\"#\" class=\"read-btn\">查看源码 →</a>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"col-md-4\">\n");
      out.write("				<div class=\"blog-card\">\n");
      out.write("					<img src=\"/images/code/code-2.jpg\">\n");
      out.write("					<div class=\"blog-content\">\n");
      out.write("						<h3>响应式博客模板</h3>\n");
      out.write("						<p>\n");
      out.write("							适配 PC 与移动端的现代博客 UI，支持暗黑模式与动态主题切换。\n");
      out.write("						</p>\n");
      out.write("						<a href=\"#\" class=\"read-btn\">查看源码 →</a>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"col-md-4\">\n");
      out.write("				<div class=\"blog-card\">\n");
      out.write("					<img src=\"/images/code/code-3.jpg\">\n");
      out.write("					<div class=\"blog-content\">\n");
      out.write("						<h3>AI 智能问答系统</h3>\n");
      out.write("						<p>\n");
      out.write("							基于 OpenAI API 构建的智能聊天系统，支持上下文与知识库检索。\n");
      out.write("						</p>\n");
      out.write("						<a href=\"#\" class=\"read-btn\">查看源码 →</a>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</section>\n");
      out.write("\n");
      out.write("	<!-- Footer -->\n");
      out.write("	<footer class=\"footer\">\n");
      out.write("		<p>© 2026 NovaTech Blog · Designed with Modern UI</p>\n");
      out.write("	</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
